[phases.setup]
nixPkgs = [
  "gcc",
  "python3",
  "python3-pip",
  "python3-dev",
  "ffmpeg",
  "build-essential"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install wheel setuptools",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"