[phases.setup]
nixPkgs = [
    "ffmpeg",
    "gcc",
    "git",
    "python39",
    "python39Packages.pip"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install -r requirements.txt --no-cache-dir"
]

[start]
cmd = "python main.py"

[build]
builder = "nixpacks"