[phases.setup]
nixPkgs = ["python39", "gcc", "ffmpeg"]
aptPkgs = ["python3-dev", "build-essential"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["true"]

[start]
cmd = "python main.py"